#
# Module manifest for module 'update-git'
#
# Generated by: wxyz
#
# Generated on: 7/5/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\update-gitrepos.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '45b6ebcc-9817-4974-b2a6-670b05cf39ca'

# Author of this module
Author = 'Rebecca Turner'

# Copyright statement for this module
Copyright = 'Public domain'

#Description of the functionality provided by this module
Description = 'Utility to help keep many git repos up to date.'

# Minimum version of the Windows PowerShell engine required by this module
# Uses $PSScriptRoot
PowerShellVersion = '3.0'

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Functions to export from this module
FunctionsToExport = @('Update-GitRepos')

# Cmdlets to export from this module
CmdletsToExport = @('Update-GitRepos')

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @('up')

# List of all files packaged with this module
# FileList = @(".\GitRepos.txt",)


#07/12/2016  11:03 AM               915 flow.dot
#07/12/2016  11:03 AM             4,666 flow.txt
#07/11/2016  12:53 AM               487 GitRepos.txt
#07/09/2016  05:31 PM               160 Makefile
#07/11/2016  01:25 AM             4,425 Readme.md
#07/12/2016  11:10 AM             4,412 update-gitrepos.psd1
#07/11/2016  01:22 AM             6,129 update-gitrepos.psm1

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
	ProjectUri = 'https://github.com/9999years/Update-GitRepos'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

